version: '3.8'

services:
  nginx:
    build:
      context: ./maindocker
      dockerfile: Dockerfile
    container_name: nginx-main
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    networks:
      - nginx-network
  redblue:
    build:
      context: ./redbluedocker
      dockerfile: Dockerfile
    container_name: nginx-redblue
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

